### ISSUE TITLE
Dependency modules

### ISSUE THREAD

**Issue by Zooman090** [adasq/dropbox-v2-api#10]
Hi, I have some issue with your module. This module use `"request": "2.67.0"`. Request module have node-uuid and tough-cookie modules and they make issue for me. i can't compile my electron app.
`npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130`
`npm WARN deprecated node-uuid@1.4.8: Use uuid module instead`

Please update your `request` module for laste version because in last version all these problems are resolved.
Thanks.

**Comment by adasq** [comment]
Latest version of `request` (`2.83.0`) has been added. New version of `dropbox-v2-api` (`2.1.10`) has been published. Thanks. Closing.
