### ISSUE TITLE
upload session start/append/finish

### ISSUE THREAD

**Issue by jprons02** [adasq/dropbox-v2-api#1099]
I'm working on using upload session start, append and finish for files over 150MB. I'm getting this error, sessionStart error:  {}
I have a file on my node server i'm trying to upload. I believe the error has to be in the variables firstUploadChunkStream and secondUploadChunkStream. I'm new to node and streams and might not be understanding what is needed. See my code below, thank you.

`const axios = require('axios');
const {dropboxAccessToken} = require('../../config/dev');
const {dropboxKey} = require('../../config/dev');
const {dropboxSecret} = require('../../config/dev');
const fs = require('fs');
const multer = require('multer');
const upload = multer({dest: 'temp_files_to_upload'});

const util = require('util');
const dropbox = require('dropbox-v2-api').authenticate({ token: dropboxAccessToken });

module.exports = app => {

    app.post('/api/testupload/:file/:size', upload.single('myFile'), (req, res) => {
        console.log('begin upload process...');
        const deleteTempFile = (response) => {
            if(response) {
                console.log('file has been successfully uploaded to dropbox...');
                console.log('deleting temp file from /temp_files_to_upload...');
                (async () => {
                    try {
                        await fs.promises.unlink(`temp_files_to_upload/${req.file.filename}`);
                    }   
                    catch(error) {
                        console.log(error);
                    }
                })();
            }
        }

        const getResponseFromBigFile = () => {
            const CHUNK_LENGTH = 100;
            
            const firstUploadChunkStream = () => fs.createReadStream(`temp_files_to_upload/${req.file.filename}`, {'1': CHUNK_LENGTH});
            const secondUploadChunkStream = () => fs.createReadStream(`temp_files_to_upload/${req.file.filename}`, {'2': CHUNK_LENGTH});

            sessionStart((sessionId) => {
                sessionAppend(sessionId, () => {
                    sessionFinish(sessionId);
                });
            });

            function sessionStart(cb) {
                console.log('session start fired...');
                dropbox({
                    resource: 'files/upload_session/start',
                    parameters: {
                        close: false
                    },
                    readStream: firstUploadChunkStream()
                }, (err, result, response) => {
                    if (err) { return console.log('sessionStart error: ', err) }
                    console.log('sessionStart result:', result);
                    cb(result.session_id);
                });
            }

            function sessionAppend(sessionId, cb) {
                console.log('session append fired...');
                dropbox({
                    resource: 'files/upload_session/append',
                    parameters: {
                        cursor: {
                            session_id: sessionId,
                            offset: CHUNK_LENGTH
                        },
                        close: false,
                    },
                    readStream: secondUploadChunkStream()
                }, (err, result, response) => {
                    if(err){ return console.log('sessionAppend error: ', err) }
                    console.log('sessionAppend result:', result);
                    cb();
                });
            }

            function sessionFinish(sessionId) {
                console.log('session finish fired...');
                dropbox({
                    resource: 'files/upload_session/finish',
                    parameters: {
                        cursor: {
                            session_id: sessionId,
                            offset: CHUNK_LENGTH * 2
                        },
                        commit: {
                            path: `/media/${req.file.originalname}`,
                            mode: 'add',
                            autorename: true,
                            mute: false
                        }
                    }
                }, (err, result, response) => {
                    if (err) { return console.log('sessionFinish error: ', err) }
                    console.log('sessionFinish result:', result);
                    res.send(result);
                });
            }

        }

        try {
            const filePath = `temp_files_to_upload/${req.file.filename}`;

            //checks if file is uploaded to temp_files_to_upload folder
            fs.access(filePath, fs.constants.F_OK, async (err) => {
                if(err) {
                    console.log('file has not been uploaded.');
                }
                //file exists, do dropbox call
                else {
                    console.log('file has been uploaded to node server...');
                    getResponseFromBigFile();
                }
            });
            
        }
        catch(error) {
          res.send(error);
        }

    });

}`

**Comment by adasq** [comment]
Hi
Both of your streams (`firstUploadChunkStream` and `secondUploadChunkStream`) seem to be specified incorrectly.

second argument of `fs.createReadStream()` requires options. You have to provide bytes start and stop position, like here:

https://github.com/adasq/dropbox-v2-api/blob/dbd29409eb8a830521d891800ff97b512dd15b90/example/partial-upload.js#L22-L25

Feel free to check how the simple example works for you, then try in more complex environment.

**Comment by jprons02** [comment]
That seems to have helped. My new issue is session append result is null. I'm expecting a session_id string from the call. Thanks.

**Comment by adasq** [comment]
there is no such thing as append `sessionID`. You basically reuse `session start` sessionId:

https://github.com/adasq/dropbox-v2-api/blob/dbd29409eb8a830521d891800ff97b512dd15b90/example/partial-upload.js#L33-L45

**Comment by jprons02** [comment]
Thanks again for the help, the example is completing the upload process but only up to 200 bytes. I have tried to build on that but have now fallen into an offset error. Dropbox api docs state offset is "the amount of data that has been uploaded so far", which in your example is hard coded and correct, but bigger files might be incorrect. 
https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-append 

error: 
sessionAppend error:  {
   error_summary: 'incorrect_offset/...',
   error: { '.tag': 'incorrect_offset', correct_offset: 100000 },
   code: 409
}

`const getResponseFromBigFile = () => {
            const CHUNK_LENGTH = 100000;
            const FILE_SIZE = parseInt(req.params.size);
            let bytesUploaded = 0;
            let isClosed = false;
            
            const uploadChunkStream = () => {
                console.log('uploadChunk called');
                let start;
                let end;

                //end
                if((bytesUploaded + CHUNK_LENGTH) >= FILE_SIZE) {
                    start = bytesUploaded;
                    end = FILE_SIZE;
                } 
                //start or continue upload
                else {
                    start = bytesUploaded;
                    end = bytesUploaded + CHUNK_LENGTH - 1;
                }
                
                console.log('start value: ' + start);
                console.log('end value: ' + end);
                
                return fs.createReadStream(`temp_files_to_upload/${req.file.filename}`, {start: start, end: end});
            }

            const dowork = () => {
                sessionStart((sessionId) => {
                    if(bytesUploaded + CHUNK_LENGTH >= FILE_SIZE) {
                        isClosed = true;
                    }
                    sessionAppend(sessionId, () => {
                        if(bytesUploaded + CHUNK_LENGTH >= FILE_SIZE) {
                            sessionFinish(sessionId);
                        }
                        else {
                            dowork();
                        }
                    })
                })
            }
            dowork();

            function sessionStart(cb) {
                console.log('sessionStart() called.');
                dropbox({
                    resource: 'files/upload_session/start',
                    parameters: {
                        close: false
                    },
                    readStream: uploadChunkStream()
                }, (err, result, response) => {
                    if (err) { return console.log('sessionStart error: ', err) }
                    console.log('sessionStart result:', result);
                    
                    bytesUploaded = bytesUploaded + CHUNK_LENGTH;
                    console.log('bytes uploaded: ' + bytesUploaded);
                    cb(result.session_id);
                });
            }
            
            
            function sessionAppend(sessionId, cb) {
                console.log('sessionAppend() called.');
                dropbox({
                    resource: 'files/upload_session/append',
                    parameters: {
                        cursor: {
                            session_id: sessionId,
                            //offset = UInt64 The amount of data that has been uploaded so far. We use this to make sure upload data isn't lost or duplicated in the event of a network error.
                            offset: bytesUploaded - 1
                        },
                        close: isClosed,
                    },
                    readStream: uploadChunkStream()
                }, (err, result, response) => {
                    if(err){ return console.log('sessionAppend error: ', err) }
                    bytesUploaded = bytesUploaded + CHUNK_LENGTH;
                    console.log('sessionAppend result:', result);
                    cb();
                    
                });

            }
            
            function sessionFinish(sessionId) {
                console.log('sessionFinish() called.');
                dropbox({
                    resource: 'files/upload_session/finish',
                    parameters: {
                        cursor: {
                            session_id: sessionId,
                            offset: bytesUploaded - 1
                            
                        },
                        commit: {
                            path: `/media/${req.file.originalname}`,
                            mode: 'add',
                            autorename: true,
                            mute: false
                        }
                    }
                }, (err, result, response) => {
                    if (err) { return console.log('sessionFinish error: ', err) }
                    console.log('sessionFinish result:', result);
                    res.send(result);
                    deleteTempFile(result);
                });
            }


 }`

**Comment by adasq** [comment]
I updated an example partial upload app:
https://github.com/adasq/dropbox-v2-api/blob/master/example/partial-upload.js
you change value of `CHUNK_LENGTH` and see how does the app logs each upload chunk size and bytes range (start / end ).

I wonder what size of file you want to upload. Is it 200B? If so,  your `sessionFinish` might be an issue, because you specify there `offset` as `bytesUploaded - 1` which seems to be `100000 - 1` which is wrong, as it exceeds your file size (`200`). But I can be wrong. Put some logs and print bytes start/end.

**Comment by jprons02** [comment]
Your new example works, tested on file sizes under 100MB and up to 2GB. Thank you!
