### ISSUE TITLE
No way to access response headers

### ISSUE THREAD

**Issue by ralphholzmann** [adasq/dropbox-v2-api#11]
Why would you need access to response headers? Because Dropbox sometimes puts information there. For example, if you get a 429 RateLimitError, the `Retry-After` header contains the number of seconds to wait before trying again.

> Your app is making too many requests for the given user or team and is being rate limited. Your app should wait for the number of seconds specified in the "Retry-After" response header before trying again. 

via https://www.dropbox.com/developers/documentation/http/documentation

Can you pass the `response` as a third argument to callbacks? I'll attempt a PR in a bit.

**Comment by adasq** [comment]
Good point. Version `2.1.13` published. it contains third param with `response`. An example:

```js
const dropboxUploadStream = dropbox({
    resource: 'files/upload',
    parameters: {
        path: '/dropbox/path/to/file.js'
    }
}, (err, result, response) => {
    // access result.headers
});
```

Closing. feel free to reopen if any problems.

**Comment by ralphholzmann** [comment]
Hot damn, that was fast. Thank you so much @adasq!
