### ISSUE TITLE
Cannot find /dist/api.json

### ISSUE THREAD

**Issue by davidjgonzalez** [adasq/dropbox-v2-api#1109]
When trying to import the Dropbox API (`const dropboxV2Api = require('dropbox-v2-api');`)

I get this error:

```
Error: Could not init action on container (POST http://0.0.0.0:32785/init): responded with error: Initialization has failed due to: Error: ENOENT: no such file or directory, open '/dist/api.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    ...
```

It appears it cannot resolve the `api.json` .. which does appear to be in the `node_modules/.../dist` folder.

**Comment by adasq** [comment]
The package is intended to be used in nodejs environment

**Comment by adasq** [comment]
closing.
