### ISSUE TITLE
No way of canceling a download

### ISSUE THREAD

**Issue by sgeier** [adasq/dropbox-v2-api#1147]
Hi, thanks for the library. I was wondering if there is a way to cancel a download once it is started?

I am working with this here:
`dropboxInstance(
    {
      resource: 'files/download',
      parameters: {
        path: filePath,
      },
    },
    (err, result) => {
      if (err) return console.log(err);
      console.log('file downloaded!', result);
      });`

I also managed to get download progress by piping everything. But I am unable to cancel the download once started.
Thanks for your help.

**Comment by adasq** [comment]
Hey! Sorry for the late response. 

Download-type requests (like `files/download`) return Node's `writableStream` (https://nodejs.org/api/stream.html#stream_writable_streams). You can try to call `.destroy()` or `.end()` on the reference.

Let me know how it works for you. In the interim, closing the issue.
