### ISSUE TITLE
How to connect existing stream and react to events

### ISSUE THREAD

**Issue by cyberwombat** [adasq/dropbox-v2-api#1156]
I am trying to connect a file upload using Fastify and [Fastify Multipart](https://github.com/fastify/fastify-multipart) and am struggling on how to connect the two.  Basically I have a ReadableStream with `on()` method for `data`,  'end` etc.  So my `data` handler might look like:
```
let fileSize = 0

// Obtain session ID here...
...

// Now handle the 'data' events
uploadedFileStrea.on('data', async (chunk) => {
    fileSize += chunk.length
    await appendSession(emitter, fileSize, sessionId)
})
```
The problem is this results in a `MaxListenersExceededWarning: Possible EventEmitter memory leak detected` error.  Any idea how to correctly join this together without creating a new emitter for each chunk?  

Thank you

**Comment by cdhowie** [comment]
The problem is likely in code you haven't shown us.

* Are you attaching this handler in a loop, or recursively?
* Is it possible that the warning is coming from a different EventEmitter in the application?

**Comment by cyberwombat** [comment]
Thanks for the feedback back. I resolved it by just making axios calls directly and not using any packages.
