### ISSUE TITLE
Please add a simple Upload Session

### ISSUE THREAD

**Issue by simatec** [adasq/dropbox-v2-api#1234]
Hello,

I am the developer of ioBroker.backitup Adapter. We use your API in the adapter

Our project has almost 60.000 installations and unfortunately users complain about the limited upload possibility of files larger than 150 MB.

It would be great if you could integrate a simple upload session.
Currently it is very cumbersome as far as I can see.

An example can be found in the OneDrive API.

There is an uploadSimple and an uploadSession.
In the upload session I only have to specify the filesize of the file and the rest is done by the ondrive-api package.

https://github.com/dkatavic/onedrive-api/blob/master/lib/items/uploadSession.js
https://github.com/dkatavic/onedrive-api#itemsuploadsession

It would be really great if you could integrate this here in the API as well.

**Comment by adasq** [comment]
Hello @simatec 👋🏻 
That's indeed true. You can only upload files up to 150MB. The official Dropbox docs suggest using the so-called "session"(https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start) 

Those methods are available in the [dropbox-v2-api](https://github.com/adasq/dropbox-v2-api) package. Example usage is  here:
https://github.com/adasq/dropbox-v2-api/blob/master/example/partial-upload.js#L45-L47

This package is meant to be solely a nodejs wrapper of Dropbox HTTP API and doesn't provide a single function you could leverage to upload 150MB+ files. 

Nevertheless, it's feasible (see the link above for an example). I hope it helps!
