### ISSUE TITLE
How does this compare to the official SDK?

### ISSUE THREAD

**Issue by twiddler** [adasq/dropbox-v2-api#1235]
I am just getting into handling my Dropbox with some TypeScript code. I found your library and [`dropbox-sdk-js`](https://github.com/dropbox/dropbox-sdk-js). As I did not find a comparison between the two, I'd like to ask:

Why should I use your library over the official one?

Thank you for your time. 🙏

**Comment by adasq** [comment]
Hey there. In a nutshell, this is a simple nodejs wrapper for Dropbox HTTP API.

**Cons:**
- no TS support 
- outdated HTTP client

**Pros:**
- simple & always up-to-date API
- lots of examples
