### ISSUE TITLE
Special character handling

### ISSUE THREAD

**Issue by dseeker** [adasq/dropbox-v2-api#17]
on line 43 there needs to be character replacement for umlauts and other special characters
https://github.com/adasq/dropbox-v2-api/blob/220d6464f83adadceedf4e4a1206f9b729ccb5ee/src/dropbox-api.js#L43

from: https://github.com/dropbox/dropbox-sdk-js/commit/585c0f2522d82c4ca3d5e63a4b920e87a6fab785

`requestOpts.headers[DB_HEADER_API_ARGS] = isObject(userParameters) ? JSON.stringify(userParameters).replace(/[\u007f-\uffff]/g, (c) => '\\u' + ('000' + c.charCodeAt(0).toString(16)).slice(-4)): '';`

**Comment by adasq** [comment]
Hey, can you give me a use-case for it? Is it file name problem?

**Comment by adasq** [comment]
@dseeker thanks for raising the problem and official repo research. 
`2.1.21` has been published. 
Closing!
