### ISSUE TITLE
global config breaks concurrent use

### ISSUE THREAD

**Issue by Sewdn** [adasq/dropbox-v2-api#2]
Hi,

thanks for this wrapper package around the Dropbox v2 HTTP endpoints.
I really like your efforts for supporting streams (and I like the simplicity of this package instead of wrapping all API calls in separate methods). I like this more then the official JavaScript SDK from Dropbox, and it feels like this will be closer to the actual available HTTP endpoints.

I have a question though, before I start using this package.

When you use dropbox.authenticate(config), this config is stored globally. I'm afraid that using this package in a system that authenticates several users simultaneously, might break things.

Say the systems authenticates for userA, using his generated (and stored accessToken), do a few calls on the dropbox api and then the system authenticates for another userB, using another accessToken. All subsequent calls for userA will be using the accessToken of userB...

I don't want to call authenticate before every call I make, certainly not when I'm chaining calls (using results of a previous request to start a new request).

I think your package would benefit from a change to localize the config to an instance of your dropbox api-wrapper, so you can start an instance for any user.

What are your thoughts on this?

**Comment by adasq** [comment]
Hi, Thanks for your feedback. I really appreciate the fact, that someone is interested in using this particular package.
I think an issue you have described is a real problem which must be covered. I will take care of it. Thanks!

**Comment by adasq** [comment]
Ok, we are now able to manage multiple dropbox sessions. As it breaks current authentication API, new version `v2.0.0` has been released.
How to create session: https://github.com/adasq/dropbox-v2-api#auth
Pull request: (https://github.com/adasq/dropbox-v2-api/pull/4)
