### ISSUE TITLE
Cant use the library on front end (React App) which is also using Node environment 

### ISSUE THREAD

**Issue by shaheryar1** [adasq/dropbox-v2-api#20]
TypeError: fs.readFileSync is not a function
loadResourcesDescriptionList
C:/Users/EG/Desktop/NodeJs/FYP/MeshDrive/meshdrive-frontend/node_modules/dropbox-v2-api/src/dropbox-api.js:213
  210 | function noop() {}
  211 | 
  212 | function loadResourcesDescriptionList() {
> 213 | 	return JSON.parse(fs.readFileSync(RESOURCES_DESCRIPTION_PATH));
  214 | }
  215 | 
  216 | function createDefaultRequestOptObject(resourceDescription){

**Comment by adasq** [comment]
Nope you can't. Use official SDH for dropbox instead.

**Comment by augustopablo** [comment]
Can't I use this package with gatsby?

**Comment by adasq** [comment]
Hey @augustopablo, unfortunately, it is for nodejs-based apps

**Comment by augustopablo** [comment]
Then what's the option for client-side? thx.
