### ISSUE TITLE
Move DROPBOX_TOKEN to a configuration

### ISSUE THREAD

**Issue by alan-null** [adasq/dropbox-v2-api#8]
An idea for an improvement.
Instead of getting `DROPBOX_TOKEN` from environment variable
```
process.env.DROPBOX_TOKEN
```

Better have a configuration file and get it from it.
```
const config = require('./../config.json');
let token = config.DROPBOX_TOKEN
```

**Comment by adasq** [comment]
breaking travis build, see `nconf`. It might solve the issue
